---
- name: Included task for Proxmox regular master
  block:
    - name: Install K3s | Run install script on regular master server | Proxmox
      tags:
        - k3s
        - install
        - regular_master
        - with_shell
      ansible.builtin.shell: >
        INSTALL_K3S_VERSION={{ k3s.version }}
        K3S_KUBECONFIG_MODE="644"
        INSTALL_K3S_EXEC="server
        --disable traefik"
        K3S_URL=https://{{ hostvars['k3s-master-01-deployer'].ansible_default_ipv4.address }}:6443
        K3S_TOKEN={{ hostvars['localhost'].k3s_token }}
        {{ k3s.path.install }}
      args:
        creates: "{{ k3s.path.bin }}"
      register: reg_k3s_regular_master
      notify: "remove_tmp"

  rescue:
    - name: ERROR | Run install script on regular master server | Display error lines
      tags:
        - error_handling
        - with_debug
      ansible.builtin.debug:
        msg: "{{ reg_k3s_regular_master.stderr_lines }}"

    - name: ERROR | Run install script on regular master server | Attempt restarting service
      tags:
        - error_handling
        - with_module
      ansible.builtin.systemd_service:
        name: k3s
        state: restarted
      register: reg_k3s_rm_service_status

    - name: ERROR | Run install script on regular master server | Uninstall remaining K3s files
      tags:
        - error_handling
        - with_shell
      ansible.builtin.shell: "{{ k3s.path.server_uninstall_bin }}"
      args:
        removes: "{{ k3s.path.bin }}"
      when: reg_k3s_rm_service_status.state != "started"

  always:
    - name: Install K3s | Verify K3s installation on regular master
      tags:
        - verify
        - with_debug
      ansible.builtin.debug:
        msg: "{{ reg_k3s_regular_master.stdout_lines }}"
