---
# defaults file for k3s-agents

# temporary directory (marked for removal)
tmp_dir: /tmp/k3s-agents
  
# K3s variables
k3s:
  version: v1.28.12+k3s1
  path:
    bin: /usr/local/bin/k3s
    install: "{{ tmp_dir }}/k3s_install.sh"
