# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Global config
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # Timezone plugin configuration
  if Vagrant.has_plugin?("vagrant-timezone")
    config.timezone.value = :host
  end

  # K3s Masters
  (1..2).each do |i|
    config.vm.define "k3s-master-0#{i}" do |master|
      master.vm.hostname = "k3s-master-0#{i}"

      # VMware_desktop provider configuration for K3s Master
      master.vm.provider "vmware_desktop" do |v, override|
        v.vmx["memsize"] = "4096"
        v.vmx["numvcpus"] = "2"
        override.vm.network "public_network", bridge: true, ip: "10.0.0.1#{i}", auto_config: true
      end

      # VirtualBox provider configuration for K3s Master
      master.vm.provider "virtualbox" do |v, override|
        v.memory = "4096"
        v.cpus = "2"
        v.linked_clone = true
        override.vm.network "private_network", ip: "10.0.0.1#{i}", auto_config: true
        override.vm.base_mac = nil
      end
    end
  end

  # K3s Workers
  (1..2).each do |i|
    config.vm.define "k3s-worker-0#{i}" do |worker|
      worker.vm.hostname = "k3s-worker-0#{i}"

      # VMware_desktop provider configuration for K3s Workers
      worker.vm.provider "vmware_desktop" do |v, override|
        v.vmx["memsize"] = "4096"
        v.vmx["numvcpus"] = "1"
        override.vm.network "public_network", bridge: true, ip: "10.0.0.2#{i}", auto_config: true
      end

      # VirtualBox provider configuration for K3s Workers
      worker.vm.provider "virtualbox" do |v, override|
        v.memory = "4096"
        v.cpus = "1"
        v.linked_clone = true
        override.vm.network "private_network", ip: "10.0.0.2#{i}", auto_config: true
        override.vm.base_mac = nil
      end
    end
  end
end