Vagrant.configure("2") do |config|
    # Global config
    config.vm.box = "bento/ubuntu-22.04"
    config.vm.provider "virtualbox" do |v|
      v.memory = "4192" 
      v.cpus = "2"
      v.linked_clone = true
    end
    
    # Hostmanager plugin config
    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true
    config.hostmanager.manage_guest = true
    config.hostmanager.ignore_private_ip = false
    config.hostmanager.include_offline = true
  
    # K3s Master
    config.vm.define "k3s-master-01" do |master|
      master.vm.hostname = "k3s-master-01"
      master.vm.provider "virtualbox" do |v|
        v.memory = "4192"
        v.cpus = "2"
      end
  
      master.vm.network "private_network", ip: "10.0.0.10", auto_config: true
  
    end
  
    # K3s Workers
    (1..2).each do |i|
      config.vm.define "k3s-worker-0#{i}" do |worker|
        worker.vm.hostname = "k3s-worker-0#{i}"
        worker.vm.provider "virtualbox" do |v|
          v.memory = "4096"
          v.cpus = "1"
        end
  
        worker.vm.network "private_network", ip: "10.0.0.2#{i}", auto_config: true
  
      end
    end
  end