deployer:
  hosts:
    k3s-master-01-deployer: # hardcoded name to provide token for nodes enrolment, DO NOT RENAME!
      ansible_host: 10.0.0.11

servers:
  hosts:
    k3s-master-02: # this name is being showed when playbook launch, you can change it as you wish to
      ansible_host: 10.0.0.12
    k3s-master-03:
      ansible_host: 10.0.0.13
#    k3s-master-04:
#      ansible_host: <IP>
agents:
  hosts:
    k3s-worker-01:
      ansible_host: 10.0.0.21
#    k3s-worker-02:
#      ansible_host: <IP>
#    k3s-worker-03:
#      ansible_host: <IP>